name: manifold_callibration
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  dio: ^5.7.0
  fl_chart: ^0.69.2
  flex_color_scheme: ^8.0.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  google_fonts: ^6.2.1
  http_mock_adapter: ^0.6.1
  hyper_router: ^0.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  # assets:
  #   - assets/test_data/
